name: Run frontend-tests

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
     - 'main'
    
jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Change to frontend directory
        run: cd ..
      - name: Change to frontend directory again 1
        run: ls
      # - name: Change to frontend directory again
      #   run: cd .\frontend\
      # - name: Install dependencies
      #   run: npm install
      # - name: Run tests
      #   run: npm test